In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 18 ms, sys: 11.7 ms, total: 29.7 ms
Wall time: 29.1 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 608 ms, sys: 160 ms, total: 768 ms
Wall time: 778 ms


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-0.57453455,  0.53667192, -0.42867695],
       [-0.51930279,  0.03032256,  0.55392112]])

In [8]:
data * 10

array([[-5.74534553,  5.36671919, -4.28676948],
       [-5.1930279 ,  0.30322556,  5.53921124]])

In [9]:
data + data

array([[-1.14906911,  1.07334384, -0.8573539 ],
       [-1.03860558,  0.06064511,  1.10784225]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### Creating ndarrays

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[2.31584178e+077, 2.31584178e+077],
        [3.45845952e-323, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.32034744e+077]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [28]:
arr2 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('float64')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

Be careful using np.string_. May truncate

If casting fails, get a ValueError

In [40]:
int_array = np.arange(10)

In [41]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [42]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
empty_uint32 = np.empty(8, dtype='u4')

In [44]:
empty_uint32

array([         0, 1342177280,          0, 1342177280,          7,
                0,  376188771, 1342179320], dtype=uint32)

### Arithmetic with Numpy Arrays

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [52]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [54]:
arr = np.arange(10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5]

5

In [57]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:8] = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Changes modifications not copies

In [60]:
arr_slice = arr[5:8]

In [61]:
arr_slice

array([12, 12, 12])

In [62]:
arr_slice[1] = 12345

In [63]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [64]:
arr_slice[:] = 64

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

To get a copy arr[5:8].copy()

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0, 2]

3

In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_values = arr3d[0].copy()

In [74]:
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = old_values

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1, 0]

array([7, 8, 9])

In [79]:
x = arr3d[1]

In [80]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1, :2]

array([4, 5])

In [90]:
arr2d[:2, 2]

array([3, 6])

In [91]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [92]:
arr2d[:2, 1:] = 0

In [93]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [95]:
data = np.random.randn(7, 4)

In [96]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [97]:
data

array([[ 0.74827002, -1.20739341, -0.1758406 ,  0.58941947],
       [ 0.09512814, -0.67278597,  0.95587972, -0.54230485],
       [-0.63049223, -0.35968659,  1.30585747, -0.73723269],
       [-2.03364341, -0.47850455, -0.1049404 , -1.70490132],
       [ 0.13022545, -0.40650637, -1.47543019,  1.75937172],
       [-0.01447175,  0.36977775,  0.21147784, -1.47356089],
       [-0.99769478, -0.94807838, -0.4811137 ,  0.57438406]])

In [98]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [99]:
data[names == 'Bob']

array([[ 0.74827002, -1.20739341, -0.1758406 ,  0.58941947],
       [-2.03364341, -0.47850455, -0.1049404 , -1.70490132]])

Boolean slicing will not fail if array is not correct length.

In [100]:
data[names == 'Bob', 2:]

array([[-0.1758406 ,  0.58941947],
       [-0.1049404 , -1.70490132]])

In [101]:
data[names == 'Bob', 3]

array([ 0.58941947, -1.70490132])

In [102]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [103]:
data[~(names == 'Bob')]

array([[ 0.09512814, -0.67278597,  0.95587972, -0.54230485],
       [-0.63049223, -0.35968659,  1.30585747, -0.73723269],
       [ 0.13022545, -0.40650637, -1.47543019,  1.75937172],
       [-0.01447175,  0.36977775,  0.21147784, -1.47356089],
       [-0.99769478, -0.94807838, -0.4811137 ,  0.57438406]])

In [104]:
cond = names == 'Bob'

In [105]:
data[~cond]

array([[ 0.09512814, -0.67278597,  0.95587972, -0.54230485],
       [-0.63049223, -0.35968659,  1.30585747, -0.73723269],
       [ 0.13022545, -0.40650637, -1.47543019,  1.75937172],
       [-0.01447175,  0.36977775,  0.21147784, -1.47356089],
       [-0.99769478, -0.94807838, -0.4811137 ,  0.57438406]])

In [107]:
mask = (names == 'Bob') | (names == 'Will')

In [108]:
mask

array([ True, False,  True,  True,  True, False, False])

In [109]:
data[mask]

array([[ 0.74827002, -1.20739341, -0.1758406 ,  0.58941947],
       [-0.63049223, -0.35968659,  1.30585747, -0.73723269],
       [-2.03364341, -0.47850455, -0.1049404 , -1.70490132],
       [ 0.13022545, -0.40650637, -1.47543019,  1.75937172]])

In [110]:
data[data < 0] = 0